set(_CATKIN_CURRENT_PACKAGE "vins_estimator")
set(vins_estimator_VERSION "0.0.0")
set(vins_estimator_MAINTAINER "qintong <qintonguav@gmail.com>")
set(vins_estimator_PACKAGE_FORMAT "1")
set(vins_estimator_BUILD_DEPENDS "roscpp")
set(vins_estimator_BUILD_EXPORT_DEPENDS "roscpp")
set(vins_estimator_BUILDTOOL_DEPENDS "catkin")
set(vins_estimator_BUILDTOOL_EXPORT_DEPENDS )
set(vins_estimator_EXEC_DEPENDS "roscpp")
set(vins_estimator_RUN_DEPENDS "roscpp")
set(vins_estimator_TEST_DEPENDS )
set(vins_estimator_DOC_DEPENDS )
set(vins_estimator_DEPRECATED "")