set(_CATKIN_CURRENT_PACKAGE "pose_graph")
set(pose_graph_VERSION "0.0.0")
set(pose_graph_MAINTAINER "tony-ws <tony-ws@todo.todo>")
set(pose_graph_PACKAGE_FORMAT "1")
set(pose_graph_BUILD_DEPENDS "camera_model")
set(pose_graph_BUILD_EXPORT_DEPENDS "camera_model")
set(pose_graph_BUILDTOOL_DEPENDS "catkin")
set(pose_graph_BUILDTOOL_EXPORT_DEPENDS )
set(pose_graph_EXEC_DEPENDS "camera_model")
set(pose_graph_RUN_DEPENDS "camera_model")
set(pose_graph_TEST_DEPENDS )
set(pose_graph_DOC_DEPENDS )
set(pose_graph_DEPRECATED "")